name: Automated Release to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.9

      - name: Install dependencies
        run: pnpm install

      - name: Bump version
        id: version
        run: npx changeset version

      - name: Commit and Tag
        env:
          HUSKY: 0
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(node -p "require('./package.json').version")
          git add .
          git commit -m "chore: release version $VERSION [skip ci]"
          git tag v$VERSION
          git push origin main --tags

      - name: Build package
        run: pnpm build

      - name: Publish to GitHub Packages
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
